version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  versioning-strategy: increase
- package-ecosystem: npm
  directory: "/packages/daemon"
  schedule:
    interval: weekly
  versioning-strategy: increase
- package-ecosystem: npm
  directory: "/packages/ui"
  schedule:
    interval: weekly
  versioning-strategy: increase
