version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Etc/UCT
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.2.4
  - dependency-name: ws
    versions:
    - 7.4.5
  - dependency-name: ts-loader
    versions:
    - 9.1.1
  - dependency-name: "@relaycorp/relaynet-core"
    versions:
    - 1.42.6
    - 1.44.0
  - dependency-name: fastify
    versions:
    - 3.13.0
    - 3.14.2
  - dependency-name: "@relaycorp/relaynet-testing"
    versions:
    - 1.1.5
  - dependency-name: "@relaycorp/cogrpc"
    versions:
    - 1.3.2
    - 1.3.4
    - 1.3.5
  - dependency-name: "@relaycorp/relaynet-poweb"
    versions:
    - 1.3.15
  - dependency-name: "@typegoose/typegoose"
    versions:
    - 7.5.0
  - dependency-name: tslint
    versions:
    - 6.1.3
  - dependency-name: mongoose
    versions:
    - 5.11.18
  - dependency-name: ts-node-dev
    versions:
    - 1.1.6
  - dependency-name: grpc
    versions:
    - 1.24.5
  - dependency-name: "@relaycorp/object-storage"
    versions:
    - 1.3.8
  - dependency-name: typescript
    versions:
    - 4.2.2
- package-ecosystem: npm
  directory: "/packages/daemon"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Etc/UCT
  open-pull-requests-limit: 99
  versioning-strategy: increase
- package-ecosystem: npm
  directory: "/packages/ui"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Etc/UCT
  open-pull-requests-limit: 99
  versioning-strategy: increase
