version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  versioning-strategy: increase
  commit-message:
    prefix: "fix(deps):"
    prefix-development: "chore(deps):"
- package-ecosystem: npm
  directory: "/packages/daemon"
  schedule:
    interval: weekly
  versioning-strategy: increase
  commit-message:
    prefix: "fix(deps):"
    prefix-development: "chore(deps):"
- package-ecosystem: npm
  directory: "/packages/ui"
  schedule:
    interval: weekly
  versioning-strategy: increase
  commit-message:
    prefix: "fix(deps):"
    prefix-development: "chore(deps):"
