branches: [master]
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/npm"
    - npmPublish: false
  - - "@semantic-release/exec"
    - prepareCmd: echo ${nextRelease.version} > version.txt
  - - "@semantic-release/github"
    - assets: []
